syntax = "proto3";

package productservice;
import "google/protobuf/timestamp.proto";

option go_package = "github.com/zxCroshka/ecommerce/shared/productservice/gen/go;productservicev1";


service Products{
	//
	rpc GetProduct(GetProductRequest) returns (GetProductResponse);
	//
	rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse);
	//
	rpc ReleaseStock(ReleaseStockRequest) returns (ReleaseStockResponse);
}


message GetProductRequest{
	int64 product_id = 1;
}
message Product{
	int64 id = 1;
	string name = 2;
	string description = 3;
	int64 price = 4;
	int64 stock = 5;
	string category = 6;
	repeated string images = 7;
	bool is_active = 9;
	google.protobuf.Timestamp created_at = 8;
	google.protobuf.Timestamp updated_at = 10;
}
message GetProductResponse {
	Product product = 1;
}

message ReserveStockRequest{
	int64 product_id = 1;
	int64 quantity = 2;
}

message ReserveStockResponse{

}
message ReleaseStockRequest{
	int64 product_id = 1;
	int64 quantity = 2;
}
message ReleaseStockResponse{

}