service:
  name: "ecommerce-api-userservice"
  environment: "local"

http:
  host: "0.0.0.0"
  port: 8082


grpc:
  host: "0.0.0.0"
  port: 9090

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "ecommerce"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

kafka:
  brokers:
    - "localhost:9092"

kafka_ui:
  url: "http://localhost:8081"

token_ttl: "1h"
access_token_expire_in: "15m"
refresh_token_expire_in: "168h"
jwt_secret: "local-dev-secret-key-2024-change-me-in-production"