service:
  name: "ecommerce-service-cart"
  environment: "local"

grpc:
  port: 9093
  internal_token: "local-dev-cart-service-token-change-me"

user_service:
  address: "127.0.0.1:9090"
  timeout: "2s"

product_service:
  address: "127.0.0.1:9091"
  retry_count: 3
  timeout: "2s"

cart:
  ttl: "168h"
  max_product_quantity: 99

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 2

logging:
  level: "debug"
  format: "text"
