service:
  name: "ecommerce-service-product"
  environment: "local"

grpc:
  host: "0.0.0.0"
  port: 9091
  internal_token: "local-dev-product-service-token-change-me"

user_service:
  address: "127.0.0.1:9090"

postgres:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "ecommerce"
  sslmode: "disable"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 1
  ttl:
    product_cache: "5m"
    products_list_cache: "5m"

kafka:
  brokers:
    - "localhost:9092"
  topic:
    product_updated: "product.updated"


pagination:
  default_limit: 20
  max_limit: 100
