syntax = "proto3";


package userservice;


option go_package = "github.com/zxCroshka/ecommerce/shared/userservice/gen/go;userservicev1";
//
service User {
	//
	rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
	//
	rpc GetUser(GetUserRequest) returns (GetUserResponse);
}



message ValidateTokenRequest{
	string token = 1;
}


message ValidateTokenResponse {
	int64 user_id = 1;
	reserved 2;
	reserved "is_admin";
	string role = 3;
}

message GetUserRequest {
  int64 user_id = 1;
}

message GetUserResponse{
	string email = 1;
	reserved 2;
	reserved "is_admin";
	string name = 3;
	string role = 4;
}
